### ISSUE TITLE
ReferenceError: performance is not defined when using NPM

### ISSUE THREAD

**Issue by srsgores** [asayerio/js#1]
I get the following error when trying to integrate asayer via NPM in an emberjs app:

> ReferenceError: performance is not defined
    at eval (webpack://__ember_auto_import__/./node_modules/@asayerio/tracker/lib/modules/performance.js?:6:26)
    at Module../node_modules/@asayerio/tracker/lib/modules/performance.js (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor.js:103444:1)
    at __webpack_require__ (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor.js:103672:30)
    at eval (webpack://__ember_auto_import__/./node_modules/@asayerio/tracker/lib/app/index.js?:8:78)
    at Module../node_modules/@asayerio/tracker/lib/app/index.js (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor.js:103276:1)
    at __webpack_require__ (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor.js:103672:30)
    at eval (webpack://__ember_auto_import__/./node_modules/@asayerio/tracker/lib/index.js?:4:62)
    at Module../node_modules/@asayerio/tracker/lib/index.js (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor.js:103336:1)
    at __webpack_require__ (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor.js:103672:30)
    at Module.eval [as callback] (webpack://__ember_auto_import__/C:/Users/user/AppData/Local/Temp/broccoli-23480bkxiS0bkXgh/cache-326-bundler/staging/app.js?:15:52)
    at Module.exports (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor\loader\loader.js:106:1)
    at Module._reify (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor\loader\loader.js:143:1)
    at Module.reify (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor\loader\loader.js:130:1)
    at Module.exports (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor\loader\loader.js:104:1)
    at requireModule (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\vendor\loader\loader.js:27:1)
    at Class._extractDefaultExport (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\addon-tree-output\ember-resolver\resolvers\classic\index.js:463:1)
    at Class.resolveOther (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\addon-tree-output\ember-resolver\resolvers\classic\index.js:123:1)
    at Class.resolve (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\addon-tree-output\ember-resolver\resolvers\classic\index.js:186:1)
    at resolve (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\container\index.js:1223:1)
    at Registry.resolve (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\container\index.js:763:1)
    at Registry.resolve (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\container\index.js:766:1)
    at factoryFor (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\container\index.js:306:1)
    at instantiateFactory (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\container\index.js:359:1)
    at lookup (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\container\index.js:296:1)
    at Container.lookup (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\container\index.js:137:1)
    at Class.lookup (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\runtime\lib\mixins\container_proxy.js:81:1)
    at PrivateRouter.getRoute (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\routing\lib\system\router.js:101:1)
    at UnresolvedRouteInfoByParam.fetchRoute (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\router_js.js:830:1)
    at UnresolvedRouteInfoByParam.get route [as route] (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\router_js.js:742:1)
    at URLTransitionIntent.applyToState (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\router_js.js:1355:1)
    at PrivateRouter.getTransitionByIntent (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\router_js.js:1499:1)
    at PrivateRouter.transitionByIntent (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\router_js.js:1454:1)
    at PrivateRouter.doTransition (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\router_js.js:1589:1)
    at PrivateRouter.handleURL (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\router_js.js:2051:1)
    at Router._doURLTransition (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\routing\lib\system\router.js:422:1)
    at Router.handleURL (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\-internals\routing\lib\system\router.js:418:1)
    at Class.visit (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\@ember\application\instance.js:259:1)
    at I:\Backups\GitHub\media-streamer\node_modules\fastboot\src\ember-app.js:294:28
    at invokeCallback (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\rsvp.js:493:1)
    at publish (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\rsvp.js:476:1)
    at C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\ember-testing\lib\ext\rsvp.js:19:1
    at invokeWithOnError (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\backburner.js:347:1)
    at Queue.flush (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\backburner.js:229:1)
    at DeferredActionQueues.flush (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\backburner.js:426:1)
    at Backburner._end (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\backburner.js:960:1)
    at Backburner._boundAutorunEnd (C:\Users\user\AppData\Local\Temp\broccoli-23480bkxiS0bkXgh\out-342-broccoli_merge_trees\assets\backburner.js:629:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```javascript
import Tracker from "@asayerio/tracker";

export default class ApplicationRoute extends Route {
	afterModel(receivedModel, transition) {
		const tracker = new Tracker({
			projectID: 7671697170555814
		});
		tracker.start();
	}
}
```

**Comment by estradino** [comment]
If you're using Ember CLI v2.15 or higher, try adding the following lines in **ember-cli-build.js**:

```
app.import('node_modules/@asayerio/tracker/lib/index.js', {
using: [
    { transformation: 'amd', as: 'Tracker' }
  ]
});
```

Let us know if that helps.

**Comment by estradino** [comment]
@srsgores was the above helpful?

**Comment by estradino** [comment]
Closed.

**Comment by srsgores** [comment]
This does not work; I get the following error:

> C:\Users\user\AppData\Local\Temp\broccoli-12680MQmKW0o82qv1\out-344-broccoli_merge_trees\assets\vendor.js:72831
> import App from './app';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at new Script (vm.js:99:7)
>     at VMSandbox.eval (I:\Backups\GitHub\media-streamer\node_modules\fastboot\src\vm-sandbox.js:13:22)
>     at I:\Backups\GitHub\media-streamer\node_modules\fastboot\src\ember-app.js:190:15
>     at Array.forEach (<anonymous>)
>     at EmberApp.loadAppFiles (I:\Backups\GitHub\media-streamer\node_modules\fastboot\src\ember-app.js:187:21)
>     at EmberApp.retrieveSandboxedApp (I:\Backups\GitHub\media-streamer\node_modules\fastboot\src\ember-app.js:235:10)
>     at new EmberApp (I:\Backups\GitHub\media-streamer\node_modules\fastboot\src\ember-app.js:61:21)
>     at FastBoot._buildEmberApp (I:\Backups\GitHub\media-streamer\node_modules\fastboot\src\index.js:114:17)
>     at new FastBoot (I:\Backups\GitHub\media-streamer\node_modules\fastboot\src\index.js:52:10)
>     at I:\Backups\GitHub\media-streamer\node_modules\ember-cli-fastboot\index.js:335:29
